### ISSUE TITLE
WPF中登录中程序卡死

### ISSUE THREAD

**Issue by WeiMiao-Xin** [Xcube-Studio/FluentCore#11]
在调用以下方法
`var res = (StandardResponseModel)(auth.AuthenticateAsync().GetAwaiter().GetResult()).Item1;`
中的“**HttpHelper.HttpPostAsync**”方法
`using var res = await HttpHelper.HttpPostAsync($"{this.YggdrasilServerUrl}/authenticate", content);`
第67行
`var res = await HttpClient.SendAsync(requestMessage);`
使用“**HttpClient.SendAsync**”这个方法会导致卡死，我尝试改成
`var res = HttpClient.Send(requestMessage);`
测试正常执行

**Comment by xuan2006** [comment]
emmmm
我这边暂时没有未迁移的账户了
没法测试Yggdrasil验证
你试试await auth.AuthenticateAsync()
异步调用可能会有帮助
